### ISSUE TITLE
Can you tell me the steps I need to take for this to work? [Question]

### ISSUE THREAD

**Issue by benjam-es** [ThePHPGuys/broadlink#1]
I have reset the device to slow blue light and I  try to run the discover code but get a response of an empty array.

**Comment by misterx** [comment]
@benjam-es  Because your device is not connected to network. Discover function find in network all connected devices. You must configure device via your phone before (setup wifi network and password).

**Comment by benjam-es** [comment]
I currently have it configured with my iPhone, and my mac running the php, and iphone and broadlink are connected to my wifi. I am running the script on php 7.1.14 and get the following error

```
PHP Fatal error:  Uncaught Exception: Unknown device in src/Device/DeviceResolver.php on line 46
```

**Comment by misterx** [comment]
@benjam-es I have updated source, now you can see your device id. Please update source and give me received ID on error and what the device you are using.

**Comment by benjam-es** [comment]
Unknown device: 279d

Hex 279d / ID 10141

Im not sure the code had even converted it to hex before checking it within the array? your new addition using dechex doesn't seem to be used elsewhere, so i've got the real ID and hex ID above.

**Comment by misterx** [comment]
@benjam-es Thanks. You are right. But all other libraries using hex device id. This is convention, so that will simplify search in google ;)

**Comment by misterx** [comment]
@benjam-es I've added your device. But i'm afraid that your device doesn't support internal thermometer. So i should create a new class for RM3 device.
